---
docker_version: 1.6.2
docker_port: 2375
docker_compose_version: 1.3.0
docker_compose_path: ./bin/docker-compose

env_values:
  - { key: DOCKER_HOST, value: "tcp://localhost:{{ docker_port }}" }
  - { key: API_MOUNT_DIR, value: "/opt/app" }
  - { key: SWIFT_MOUNT_DIR, value: "/opt/swift" }
  - { key: SWIFT_SET_PASSWORDS, value: "replaceme" }
  - { key: MYSQL_ROOT_PASSWORD, value: "replaceme" }
  - { key: MYSQL_DATABASE, value: "elixir" }
  - { key: MYSQL_USER, value: "elixir" }
  - { key: MYSQL_PASSWORD, value: "elixir" }
  - { key: MYSQL_MOUNT_DIR, value: "/opt/mysql" }
  - { key: PATH, value: "{{ ansible_env.PWD }}/bin:$PATH" }
